const def: any = {
  accessLogs: ["admin_index", "admin_request", "admin_queryLog"],
  allowedlists: [
    "admin_add",
    "admin_index",
    "admin_edit",
    "admin_delete",
    "index",
  ],
  api: [
    "openapi",
    "viewDeprecatedFunctionUse",
    "getAllApis",
    "getApiInfo",
    "rest",
  ],
  attributes: [
    "index",
    "add",
    "download",
    "add_attachment",
    "add_threatconnect",
    "edit",
    "editField",
    "view",
    "viewPicture",
    "delete",
    "restore",
    "deleteSelected",
    "getMassEditForm",
    "editSelected",
    "search",
    "checkComposites",
    "downloadAttachment",
    "returnAttributes",
    "text",
    "rpz",
    "bro",
    "reportValidationIssuesAttributes",
    "generateCorrelation",
    "fetchViewValue",
    "fetchEditForm",
    "attributeReplace",
    "downloadSample",
    "pruneOrphanedAttributes",
    "checkOrphanedAttributes",
    "updateAttributeValues",
    "hoverEnrichment",
    "describeTypes",
    "attributeStatistics",
    "addTag",
    "removeTag",
    "toggleCorrelation",
    "toggleToIDS",
    "checkAttachments",
    "exportSearch",
  ],
  auditLogs: ["admin_index", "eventIndex", "fullChange", "returnDates"],
  authKeys: ["index", "delete", "edit", "add", "view", "pin"],
  cerebrates: [
    "index",
    "add",
    "edit",
    "delete",
    "view",
    "pull_orgs",
    "pull_sgs",
    "preview_orgs",
    "download_org",
    "preview_sharing_groups",
    "download_sg",
  ],
  communities: ["index", "view", "requestAccess"],
  correlationExclusions: ["index", "delete", "add", "edit", "view", "clean"],
  correlations: [
    "top",
    "generateTopCorrelations",
    "overCorrelations",
    "switchEngine",
    "truncate",
    "generateOccurrences",
  ],
  cryptographicKeys: ["add", "delete", "view"],
  dashboards: [
    "index",
    "getForm",
    "updateSettings",
    "getEmptyWidget",
    "renderWidget",
    "import",
    "export",
    "saveTemplate",
    "listTemplates",
    "deleteTemplate",
  ],
  decayingModel: [
    "update",
    "export",
    "import",
    "view",
    "index",
    "add",
    "edit",
    "delete",
    "enable",
    "disable",
    "decayingTool",
    "getAllDecayingModels",
    "decayingToolBasescore",
    "decayingToolSimulation",
    "decayingToolRestSearch",
    "decayingToolComputeSimulation",
  ],
  decayingModelMapping: ["viewAssociatedTypes", "linkAttributeTypeToModel"],
  eventBlocklists: ["index", "add", "edit", "delete", "massDelete"],
  eventDelegations: [
    "view",
    "delegateEvent",
    "acceptDelegation",
    "deleteDelegation",
    "index",
  ],
  eventGraph: ["view", "viewPicture", "add", "delete"],
  eventReports: [
    "add",
    "view",
    "getProxyMISPElements",
    "viewSummary",
    "edit",
    "delete",
    "restore",
    "index",
    "extractAllFromReport",
    "extractFromReport",
    "replaceSuggestionInReport",
    "importReportFromUrl",
    "reportFromEvent",
  ],
  events: [
    "index",
    "filterEventIndex",
    "viewEventAttributes",
    "view",
    "removePivot",
    "add",
    "addIOC",
    "add_misp_export",
    "upload_stix",
    "merge",
    "populate",
    "edit",
    "delete",
    "unpublish",
    "publishSightings",
    "publish",
    "alert",
    "contact",
    "automation",
    "export",
    "downloadExport",
    "restSearchExport",
    "xml",
    "nids",
    "hids",
    "csv",
    "downloadOpenIOCEvent",
    "proposalEventIndex",
    "reportValidationIssuesEvents",
    "addTag",
    "removeTag",
    "freeTextImport",
    "saveFreeText",
    "stix2",
    "stix",
    "filterEventIdsForPush",
    "checkuuid",
    "pushProposals",
    "exportChoice",
    "importChoice",
    "upload_sample",
    "viewGraph",
    "updateGraph",
    "getEventTimeline",
    "getDistributionGraph",
    "getEventGraphReferences",
    "getEventGraphTags",
    "getEventGraphGeneric",
    "getReferenceData",
    "getObjectTemplate",
    "viewGalaxyMatrix",
    "viewClusterRelations",
    "delegation_index",
    "queryEnrichment",
    "handleModuleResults",
    "importModule",
    "exportModule",
    "toggleCorrelation",
    "checkPublishedStatus",
    "pushEventToZMQ",
    "pushEventToKafka",
    "getEventInfoById",
    "enrichEvent",
    "addEventLock",
    "removeEventLock",
    "checkLocks",
    "getEditStrategy",
    "upload_analysis_file",
    "cullEmptyEvents",
    "restoreDeletedEvents",
    "recoverEvent",
    "runTaxonomyExclusivityCheck",
    "generateCount",
    "protect",
    "unprotect",
  ],
  favouriteTags: ["toggle", "getToggleField"],
  feeds: [
    "loadDefaultFeeds",
    "index",
    "view",
    "feedCoverage",
    "importFeeds",
    "add",
    "edit",
    "delete",
    "fetchFromFeed",
    "fetchFromAllFeeds",
    "getEvent",
    "previewIndex",
    "previewEvent",
    "enable",
    "disable",
    "fetchSelectedFromFreetextIndex",
    "cacheFeeds",
    "compareFeeds",
    "toggleSelected",
    "searchCaches",
  ],
  galaxies: [
    "index",
    "update",
    "wipe_default",
    "view",
    "delete",
    "enable",
    "disable",
    "toggle",
    "import",
    "pushCluster",
    "export",
    "selectGalaxy",
    "selectGalaxyNamespace",
    "selectCluster",
    "attachCluster",
    "attachMultipleClusters",
    "viewGraph",
    "showGalaxies",
    "forkTree",
    "relationsGraph",
  ],
  galaxyClusterBlocklists: ["index", "add", "edit", "delete", "massDelete"],
  galaxyClusterRelations: ["index", "view", "add", "edit", "delete"],
  galaxyClusters: [
    "index",
    "view",
    "add",
    "edit",
    "publish",
    "unpublish",
    "detach",
    "delete",
    "restore",
    "viewCyCatRelations",
    "viewGalaxyMatrix",
    "updateCluster",
    "viewRelations",
    "viewRelationTree",
  ],
  galaxyElements: ["index", "delete", "flattenJson"],
  jobs: [
    "index",
    "getError",
    "getGenerateCorrelationProgress",
    "getProgress",
    "cache",
    "clearJobs",
  ],
  logs: [
    "index",
    "admin_index",
    "event_index",
    "admin_search",
    "returnDates",
    "pruneUpdateLogs",
    "testForStolenAttributes",
  ],
  modules: ["queryEnrichment", "index"],
  news: ["index", "admin_index", "add", "edit", "delete"],
  noticelists: [
    "index",
    "update",
    "toggleEnable",
    "enableNoticelist",
    "getToggleField",
    "view",
    "delete",
    "preview_entries",
  ],
  objectReferences: ["add", "delete", "view", "bulkAdd"],
  objectTemplateElements: ["viewElements"],
  objectTemplates: [
    "objectMetaChoice",
    "objectChoice",
    "view",
    "delete",
    "index",
    "update",
    "activate",
    "getToggleField",
    "getRaw",
    "possibleObjectTemplates",
  ],
  objects: [
    "revise_object",
    "add",
    "get_row",
    "edit",
    "editField",
    "fetchViewValue",
    "fetchEditForm",
    "quickFetchTemplateWithValidObjectAttributes",
    "quickAddAttributeForm",
    "delete",
    "view",
    "orphanedObjectDiagnostics",
    "proposeObjectsFromAttributes",
    "groupAttributesIntoObject",
    "createFromFreetext",
  ],
  orgBlocklists: ["index", "add", "edit", "delete"],
  organisations: [
    "index",
    "admin_add",
    "admin_edit",
    "admin_delete",
    "admin_generateuuid",
    "view",
    "fetchOrgsForSG",
    "fetchSGOrgRow",
    "getUUIDs",
    "admin_merge",
  ],
  pages: ["display"],
  posts: ["pushMessageToZMQ", "add", "edit", "delete"],
  regexp: [
    "admin_add",
    "admin_index",
    "admin_edit",
    "admin_delete",
    "index",
    "admin_clean",
    "cleanRegexModifiers",
  ],
  restClientHistory: ["index", "delete"],
  roles: [
    "view",
    "admin_add",
    "admin_edit",
    "admin_delete",
    "index",
    "admin_set_default",
  ],
  servers: [
    "index",
    "previewIndex",
    "previewEvent",
    "compareServers",
    "filterEventIndex",
    "add",
    "edit",
    "delete",
    "eventBlockRule",
    "pull",
    "push",
    "serverSettingsReloadSetting",
    "serverSettings",
    "startWorker",
    "stopWorker",
    "getWorkers",
    "idTranslator",
    "getSubmodulesStatus",
    "getSetting",
    "serverSettingsEdit",
    "killAllWorkers",
    "restartWorkers",
    "restartDeadWorkers",
    "deleteFile",
    "uploadFile",
    "fetchServersForSG",
    "postTest",
    "getRemoteUser",
    "testConnection",
    "startZeroMQServer",
    "stopZeroMQServer",
    "statusZeroMQServer",
    "purgeSessions",
    "clearWorkerQueue",
    "getVersion",
    "getPyMISPVersion",
    "checkout",
    "update",
    "ondemandAction",
    "updateProgress",
    "getSubmoduleQuickUpdateForm",
    "updateSubmodule",
    "getInstanceUUID",
    "cache",
    "updateJSON",
    "createSync",
    "import",
    "resetRemoteAuthKey",
    "changePriority",
    "releaseUpdateLock",
    "dbSchemaDiagnostic",
    "dbConfiguration",
    "cspReport",
    "removeOrphanedCorrelations",
    "queryAvailableSyncFilteringRules",
    "getAvailableSyncFilteringRules",
    "pruneDuplicateUUIDs",
    "removeDuplicateEvents",
    "upgrade2324",
    "cleanModelCaches",
    "updateDatabase",
    "ipUser",
    "rest",
  ],
  shadowAttributes: [
    "accept",
    "discard",
    "add",
    "download",
    "add_attachment",
    "edit",
    "delete",
    "view",
    "viewPicture",
    "index",
    "discardSelected",
    "acceptSelected",
    "generateCorrelation",
  ],
  sharingGroupBlueprints: [
    "index",
    "add",
    "edit",
    "delete",
    "view",
    "viewOrgs",
    "execute",
    "detach",
  ],
  sharingGroups: [
    "add",
    "edit",
    "delete",
    "index",
    "view",
    "addOrg",
    "removeOrg",
    "addServer",
    "removeServer",
  ],
  sightingdb: ["add", "edit", "delete", "index", "requestStatus", "search"],
  sightings: [
    "add",
    "advanced",
    "quickAdd",
    "quickDelete",
    "delete",
    "index",
    "listSightings",
    "viewSightings",
    "bulkSaveSightings",
    "filterSightingUuidsForPush",
  ],
  tagCollections: [
    "add",
    "import",
    "view",
    "edit",
    "delete",
    "addTag",
    "removeTag",
    "index",
    "getRow",
  ],
  tags: [
    "index",
    "add",
    "quickAdd",
    "edit",
    "delete",
    "view",
    "showEventTag",
    "showAttributeTag",
    "viewTag",
    "selectTaxonomy",
    "selectTag",
    "tagStatistics",
    "attachTagToObject",
    "removeTagFromObject",
    "viewGraph",
    "search",
    "modifyTagRelationship",
  ],
  tasks: ["index", "setTask"],
  taxiiServers: [
    "index",
    "add",
    "edit",
    "delete",
    "view",
    "push",
    "getRoot",
    "getCollections",
    "collectionsIndex",
    "objectsIndex",
    "objectView",
  ],
  taxonomies: [
    "index",
    "view",
    "taxonomy_tags",
    "export",
    "enable",
    "disable",
    "import",
    "update",
    "addTag",
    "hideTag",
    "unhideTag",
    "disableTag",
    "taxonomyMassConfirmation",
    "taxonomyMassHide",
    "taxonomyMassUnhide",
    "delete",
    "toggleRequired",
    "toggleHighlighted",
    "normalizeCustomTagsToTaxonomyFormat",
  ],
  templateElements: [
    "index",
    "templateElementAddChoices",
    "add",
    "edit",
    "delete",
  ],
  templates: [
    "index",
    "edit",
    "view",
    "add",
    "saveElementSorting",
    "delete",
    "templateChoices",
    "populateEventFromTemplate",
    "submitEventPopulation",
    "uploadFile",
    "deleteTemporaryFile",
  ],
  threads: ["viewEvent", "view", "index"],
  userSettings: [
    "index",
    "view",
    "setSetting",
    "getSetting",
    "delete",
    "setHomePage",
    "eventIndexColumnToggle",
  ],
  users: [
    "view",
    "request_API",
    "unsubscribe",
    "edit",
    "change_pw",
    "admin_index",
    "admin_filterUserIndex",
    "admin_view",
    "admin_add",
    "admin_edit",
    "admin_delete",
    "admin_massToggleField",
    "updateLoginTime",
    "login",
    "routeafterlogin",
    "logout",
    "resetauthkey",
    "resetAllSyncAuthKeys",
    "histogram",
    "terms",
    "downloadTerms",
    "checkAndCorrectPgps",
    "admin_quickEmail",
    "admin_email",
    "initiatePasswordReset",
    "otp",
    "hotp",
    "totp_new",
    "totp_delete",
    "email_otp",
    "statistics",
    "tagStatisticsGraph",
    "verifyGPG",
    "verifyCertificate",
    "searchGpgKey",
    "fetchGpgKey",
    "getGpgPublicKey",
    "checkIfLoggedIn",
    "admin_monitor",
    "register",
    "registrations",
    "discardRegistrations",
    "acceptRegistrations",
    "updateToAdvancedAuthKeys",
    "notificationSettings",
    "viewPeriodicSummary",
    "admin_destroy",
    "logout401",
    "forgot",
    "password_reset",
  ],
  warninglists: [
    "index",
    "update",
    "add",
    "edit",
    "toggleEnable",
    "enableWarninglist",
    "getToggleField",
    "view",
    "import",
    "export",
    "delete",
    "checkValue",
  ],
  workflowBlueprints: [
    "update",
    "index",
    "add",
    "edit",
    "delete",
    "view",
    "import",
    "export",
  ],
  workflows: [
    "index",
    "rebuildRedis",
    "edit",
    "delete",
    "view",
    "editor",
    "executeWorkflow",
    "triggers",
    "moduleIndex",
    "moduleView",
    "toggleModule",
    "debugToggleField",
    "massToggleField",
    "checkGraph",
    "moduleStatelessExecution",
  ],
};

for (const parent in def) {
  if (Object.prototype.hasOwnProperty.call(def, parent)) {
    const element = def[parent];
    for (const route of element) {
      fetch("https://misp-02.mmisp.cert.kit.edu/" + parent + "/" + route, {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json",
          Authorization: "ahmTK4oPwmwpEKXaOChLDck2KOV3Rs2uq4HuEwa8",
        },
      }).then((response) => {
        console.log(response);
        response.json().then((data) => {
          console.log(data);
        });
      });
    }
  }
}
